### ISSUE TITLE
words like "kongish", "posts" give errors

### ISSUE THREAD

**Issue by jyutcitzi** [jyutcitzi/jyutcitzi-transliterate#9]
Traceback (most recent call last):
  File "transliterate.py", line 492, in <module>
    t = transliterate(input('Please enter your text (Quit with CTRL + C (*nix) or CTRL + Z (Windows)):\n'), **vars(args))
  File "transliterate.py", line 423, in transliterate
    outs = [assemble(factorize(out), mode=mode) if is_alphanum(out) and len(out) > 1 and out not in unparsed else out for out in outs]
  File "transliterate.py", line 423, in <listcomp>
    outs = [assemble(factorize(out), mode=mode) if is_alphanum(out) and len(out) > 1 and out not in unparsed else out for out in outs]
  File "transliterate.py", line 325, in assemble
    return hex_dict[thing] + (hex_dict[suffix_thing] if suffix != "" else "")
KeyError: '天厶`'

**Comment by jyutcitzi** [comment]
After eddb03edad4f459e7a30a7acf808f8bb7a134fe5:
tests gives  (te st s), which is exactly what we want
kongish gives  (kong i sh), which is subpar (should be kong gi sh)


This is the best for now given that we're still using the CMU dict, closing.
